apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
   matchLabels:
     app: myapp
  replicas: 3
  template:
    metadata: 
      name: ngnix
      labels:
        app: myapp
    spec:
      containers:
      - name: ngnix
        image: ngnix